apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spring-Boot-App
  labels:
    app: Spring-Boot-App
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: Spring-Boot-App-pod
      labels:
        app: springboot
    spec:
      containers:
        - name: SpringBoot
          image: huiarup/springboot:10
          ports:
            - containerPort: 9090
  selector:
   matchLabels:
    app: springboot
 
