kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: springpod
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: huiarup/springboot:11
          ports:
            - containerPort: 9090
  selector:
   matchLabels:
    app: springboot
 
